name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t minha-app .

      - name: Rodar container
        run: docker run -d -p 5000:5000 minha-app

      - name: Verificar container
        run: docker ps